del Release_Build\*.obj
del Release_Build\*.tds
del Release_Build\*.exe
del Release_Build\*.pch
del Release_Build\*.map
del Release_Build\*.ilc
del Release_Build\*.ild
del Release_Build\*.ilf
del Release_Build\*.ils
del Release_Build\*.o
del Release_Build\*.d
del Debug_Build\*.obj
del Debug_Build\*.tds
del Debug_Build\*.exe
del Debug_Build\*.pch
del Debug_Build\*.map
del Debug_Build\*.ilc
del Debug_Build\*.ild
del Debug_Build\*.ilf
del Debug_Build\*.ils
del Debug_Build\*.o
del Debug_Build\*.d
